# Experiment name of loaded model for the mesh AE
loaded_model:
  experiment:

data_mesh: # mesh data config
  batch_size: 32

training:

  max_steps: -1
  num_steps: 125 # number of steps before the next validation

  optimizer:
    learning_rate: 0.0001
    beta_1: 0.9
    beta_2: 0.99
  
  patience: 20 # number of validation steps without improvement before stopping
  decay_rate: 0.99

  loss_str: "l1"

  # ---------------------------------- not used for the moment ----------------------------------
  momentum: 0.9
  # ---------------------------------------------------------------------------------------------

model:
  dense_layers:
    - name: dense
      units: 16
      activation:
        name: prelu
      use_bias: True
    - name: dense
      units: 1
      activation:
        name: relu
      use_bias: True


